[package]
name = "streaker-rs"
version = "0.1.0"
authors = ["Eddie <eddiepie@gmail.com>"]

[dependencies]
clap = "~2.32"
regex = "1"
indexmap = "1.0.2"

[lib]
name = "streaker"
path = "src/lib.rs"

[[bin]]
name = "streaker"
path = "src/main.rs"