[package]
name = "streaker-py"
version = "0.1.0"
authors = ["Eddie <eddiepie@gmail.com>"]

[lib]
name = "streaker"
crate-type = ["dylib"]

[dependencies.cpython]
git = "https://github.com/dgrunwald/rust-cpython.git"
default-features = false
features = ["python27-sys"]